name: acservermanager
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

  fluent_ui: 3.8.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true