name: acservermanager
description: Manage your Assetto Corsa servers

version: 0.7.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:

  fluent_ui: ^3.9.0

  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3

  shared_preferences: ^2.0.13
  file_picker: ^4.3.3

  equatable: ^2.0.3
  
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2

  easy_localization: ^3.0.0
  
  #To run the server
  process_run: ^0.12.3+1

  flutter_svg: ^1.0.3

  weather_icons: ^3.0.0

  url_launcher: ^6.0.20

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svgs/